modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
modId="dark_matter"
version="${mod_version}"
displayName="Dark Matter"
authors="RinChan"
description='''Repairs any damageable item in an anvil with compact Dark Matter.'''
logoFile="assets/dark_matter/icon.png"
[[mixins]]
config="dark_matter.mixins.json"
[[dependencies.dark_matter]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.dark_matter]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
